# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burial_id', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('C14_dendro', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True, verbose_name='Absolute dating (C14/Dendro)')),
                ('absolute_age', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('individuals', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True)),
                ('secondary_burial', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True)),
                ('secondary_burial_text', models.TextField(blank=True, help_text='helptext', null=True)),
                ('displaced', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True)),
                ('displaced_text', models.TextField(blank=True, help_text='helptext', null=True)),
                ('extraordinary_burial', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True)),
                ('extraordinary_burial_text', models.TextField(blank=True, help_text='helptext', null=True)),
                ('inhumation_burial_type', models.TextField(blank=True, help_text='helptext', null=True)),
                ('bi_ritual_burial_type', models.TextField(blank=True, help_text='helptext', null=True, verbose_name='Bi-ritual burial type')),
                ('cover', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True)),
                ('length', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('width', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('diameter', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('height', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('post_holes', models.TextField(blank=True, help_text='helptext', null=True)),
                ('surface_identification_mark', models.TextField(blank=True, help_text='helptext', null=True)),
                ('erdgraebchen', models.TextField(blank=True, help_text='helptext', null=True)),
                ('other_features', models.TextField(blank=True, help_text='helptext', null=True)),
                ('arrangement', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_burial_arrangement', to='vocabs.SkosConcept')),
            ],
        ),
        migrations.CreateModel(
            name='BurialGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burial_group_id', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('name', models.TextField(blank=True, help_text='helptext', null=True)),
                ('length', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('width', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('diameter', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('height', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('burial_group_type', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_type_of_burial_group', to='vocabs.SkosConcept')),
            ],
        ),
        migrations.CreateModel(
            name='BurialSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Please provide helptext', max_length=255, null=True)),
                ('alternative_name', models.CharField(blank=True, help_text='helptext', max_length=255, null=True)),
                ('exact_location', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True)),
                ('excavation', models.CharField(blank=True, choices=[('fully excavated', 'fully excavated'), ('partly excavated', 'partly excavated')], help_text='helptext', max_length=5, null=True)),
                ('disturbance', models.TextField(blank=True, help_text='helptext', null=True)),
                ('location_of_archaeological_material_and_contact_information', models.TextField(blank=True, help_text='helptext', null=True)),
                ('absolute_dating', models.ManyToManyField(blank=True, help_text='helptext', related_name='skos_absolute_dating', to='vocabs.SkosConcept')),
                ('dating', models.ManyToManyField(blank=True, help_text='helptext', related_name='skos_dating', to='vocabs.SkosConcept')),
                ('distance_to_next_settlement', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_distance_to_next_settlement', to='vocabs.SkosConcept')),
                ('geographical_coordinate_reference_system', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_geographical_coordinate_reference_system', to='vocabs.SkosConcept')),
                ('location', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place')),
                ('topography', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_topography', to='vocabs.SkosConcept')),
                ('type_of_burial_site', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_type_of_burial_site', to='vocabs.SkosConcept')),
            ],
        ),
        migrations.CreateModel(
            name='DeadBodyRemains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.TextField(blank=True, help_text='helptext', null=True)),
                ('pathology', models.TextField(blank=True, help_text='helptext', null=True)),
                ('total_weight', models.TextField(blank=True, help_text='helptext', null=True)),
                ('age', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_age', to='vocabs.SkosConcept')),
                ('gender', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_gender', to='vocabs.SkosConcept')),
                ('temperature', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_temperature', to='vocabs.SkosConcept')),
            ],
        ),
        migrations.CreateModel(
            name='GraveGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, help_text='helptext', null=True)),
                ('burial', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, to='burials.Burial')),
                ('condition', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_condition', to='vocabs.SkosConcept')),
                ('material', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_material', to='vocabs.SkosConcept')),
                ('name', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_name_gravegood', to='vocabs.SkosConcept')),
                ('position', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_position', to='vocabs.SkosConcept')),
            ],
        ),
        migrations.CreateModel(
            name='GraveGoodOther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True)),
                ('other_organic_grave_good', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True)),
                ('other_organic_grave_good_text', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True)),
                ('burial', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, to='burials.Burial')),
            ],
        ),
        migrations.CreateModel(
            name='Urn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn_id', models.TextField(blank=True, help_text='helptext', null=True)),
                ('urn_type', models.TextField(blank=True, help_text='helptext', null=True)),
                ('variation', models.TextField(blank=True, help_text='helptext', null=True)),
                ('basic_shape', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_basic_shape_of_urn', to='vocabs.SkosConcept')),
                ('burial', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, to='burials.Burial')),
            ],
        ),
        migrations.CreateModel(
            name='UrnCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_id', models.TextField(blank=True, help_text='helptext', null=True)),
                ('upside_down', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True)),
                ('fragment', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], help_text='helptext', max_length=5, null=True)),
                ('basic_shape', models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_basic_shape_of_urn_cover', to='vocabs.SkosConcept')),
            ],
        ),
        migrations.AddField(
            model_name='urn',
            name='cover',
            field=models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, to='burials.UrnCover'),
        ),
        migrations.AddField(
            model_name='burialgroup',
            name='burial_site',
            field=models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, to='burials.BurialSite'),
        ),
        migrations.AddField(
            model_name='burialgroup',
            name='material',
            field=models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_material_burialgroup', to='vocabs.SkosConcept'),
        ),
        migrations.AddField(
            model_name='burial',
            name='burial_group',
            field=models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, to='burials.BurialGroup'),
        ),
        migrations.AddField(
            model_name='burial',
            name='burial_site',
            field=models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, to='burials.BurialSite'),
        ),
        migrations.AddField(
            model_name='burial',
            name='burial_type',
            field=models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_burial_type', to='vocabs.SkosConcept'),
        ),
        migrations.AddField(
            model_name='burial',
            name='construction',
            field=models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_burial_construction', to='vocabs.SkosConcept'),
        ),
        migrations.AddField(
            model_name='burial',
            name='cover_type',
            field=models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_type_of_burial_cover', to='vocabs.SkosConcept'),
        ),
        migrations.AddField(
            model_name='burial',
            name='grave_pit_form',
            field=models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_form_of_the_grave_pit', to='vocabs.SkosConcept'),
        ),
        migrations.AddField(
            model_name='burial',
            name='grave_pit_orientation',
            field=models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skos_orientation_of_the_grave_pit', to='vocabs.SkosConcept'),
        ),
    ]
