# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadbodyremains',
            name='burial',
            field=models.ForeignKey(blank=True, help_text='helptext', null=True, on_delete=django.db.models.deletion.CASCADE, to='burials.Burial'),
        ),
    ]
