# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bib', '0004_auto_20160205_1155'),
        ('burials', '0002_deadbodyremains_burial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burialsite',
            name='reference',
            field=models.ManyToManyField(blank=True, help_text='Please provide helptext', to='bib.Book'),
        ),
    ]
